export * from '@/src/templates/t2';
export * from '@/src/templates/t3';
export * from '@/src/templates/t1';
export * from '@/src/templates/t16';
export * from '@/src/templates/t5';
export * from '@/src/templates/t6';
export * from '@/src/templates/t7';
export * from '@/src/templates/t8';

export * from '@/src/templates/t9';
export * from '@/src/templates/t10';    
export * from '@/src/templates/t12';    
export * from '@/src/templates/t11';
export * from '@/src/templates/t13';
export * from '@/src/templates/t14';
export * from '@/src/templates/t15';
export * from '@/src/templates/t4';
export * from '@/src/templates/t17';
export * from '@/src/templates/t18';
